# Generated by Django 3.0.14 on 2021-09-04 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
