# Generated by Django 3.2.6 on 2021-09-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default=' ', upload_to='places/'),
            preserve_default=False,
        ),
    ]
